name: Build Godot Project

on:
  push: {}
  pull_request: {}

jobs:
  build-web:
    name: Build Web
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      
      - name: Build
        id: build
        uses: manleydev/build-godot-action@v1.5.0
        with:
          name: sundai-3d-game
          preset: Web
          projectDir: "game"
      
      - name: Upload Web Build
        uses: actions/upload-artifact@v3
        with:
          name: web-build
          path: ${{ github.workspace }}/${{ steps.build.outputs.build }} 